# Generated by Django 2.1.5 on 2019-04-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=64)),
                ('building_name', models.CharField(max_length=64)),
                ('building_index', models.IntegerField()),
                ('building_photo', models.FileField(upload_to='building_photo/')),
                ('De_name', models.CharField(max_length=64)),
                ('De_index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='deterioration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=64)),
                ('building_index', models.IntegerField()),
                ('De_index', models.IntegerField()),
                ('De_photo', models.FileField(upload_to='de_photo/')),
                ('degree', models.CharField(max_length=20)),
                ('element', models.CharField(max_length=20)),
                ('space', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('detail_length', models.CharField(default=0, max_length=20)),
                ('detail_width', models.CharField(default=0, max_length=20)),
            ],
        ),
    ]
